// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  ALERT_PROCESSOR: ServiceStub<import('../alert-processor/index.js').default>;
  ALERT_SYSTEM: SmartSql;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  DEMO_TOOLS: ServiceStub<import('../demo-tools/index.js').default>;
  EVENT_STORAGE: SmartBucket;
  HOTSPOT_ANALYTICS: SmartSql;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
}
