// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Queue, SmartBucket, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  EVENT_STORAGE: SmartBucket;
  HOTSPOT_DATABASE: SmartSql;
  HOTSPOT_UPDATES: Queue<import('../alert-generator').Body>;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
}
